<a href="https://colab.research.google.com/github/AI-Junction/Learn-ML/blob/LearnPandas/LearnPandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

# UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte
df = pd.read_csv("sample_data/Minimum Wage Data.csv", encoding="latin")

In [24]:
df.to_csv("sample_data/minwage.csv", encoding="utf-8")

In [25]:
df = pd.read_csv("sample_data/minwage.csv")

In [26]:
gb = df.groupby("State")

In [27]:
df.index

RangeIndex(start=0, stop=2862, step=1)

In [28]:
df.reset_index(inplace=True)

In [29]:
df.head()

,index,Unnamed: 0,Year,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
0,0,0,1968,Alabama,0.00000,0.00,1.15,8.55,1.15,8.55,34.8,...,0.00000,0.00,0.00000,0.00,NaN
1,1,1,1968,Alaska,2.10000,15.61,1.15,8.55,2.10,15.61,34.8,2.1,2.10000,15.61,2.10000,15.61,NaN
2,2,2,1968,Arizona,0.46800,3.48,1.15,8.55,1.15,8.55,34.8,18.72 - 26.40/wk(b),0.46800,3.48,0.66000,4.91,(b)
3,3,3,1968,Arkansas,0.15625,1.16,1.15,8.55,1.15,8.55,34.8,1.25/day(b),0.15625,1.16,0.15625,1.16,(b)
4,4,4,1968,California,1.65000,12.26,1.15,8.55,1.65,12.26,34.8,1.65(b),1.65000,12.26,1.65000,12.26,(b)

In [37]:
gb = df.groupby("State")
gb.get_group("Alabama").set_index("Year").head()

,index,Unnamed: 0,State,State.Minimum.Wage,State.Minimum.Wage.2020.Dollars,Federal.Minimum.Wage,Federal.Minimum.Wage.2020.Dollars,Effective.Minimum.Wage,Effective.Minimum.Wage.2020.Dollars,CPI.Average,Department.Of.Labor.Uncleaned.Data,Department.Of.Labor.Cleaned.Low.Value,Department.Of.Labor.Cleaned.Low.Value.2020.Dollars,Department.Of.Labor.Cleaned.High.Value,Department.Of.Labor.Cleaned.High.Value.2020.Dollars,Footnote
Year,,,,,,,,,,,,,,,,
1968,0,0,Alabama,0.0,0.0,1.15,8.55,1.15,8.55,34.8,...,0.0,0.0,0.0,0.0,NaN
1969,54,54,Alabama,0.0,0.0,1.15,8.11,1.15,8.11,36.7,...,0.0,0.0,0.0,0.0,NaN
1970,108,108,Alabama,0.0,0.0,1.30,8.67,1.30,8.67,38.8,...,0.0,0.0,0.0,0.0,NaN
1971,162,162,Alabama,0.0,0.0,1.30,8.30,1.30,8.30,40.5,...,0.0,0.0,0.0,0.0,NaN
1972,216,216,Alabama,0.0,0.0,1.60,9.90,1.60,9.90,41.8,...,0.0,0.0,0.0,0.0,NaN

In [32]:
gb1 = gb.get_group("Alabama").set_index("Year").head()

In [33]:
print(gb1)

      index  Unnamed: 0    State  State.Minimum.Wage  \
Year
1968      0           0  Alabama                 0.0
1969     54          54  Alabama                 0.0
1970    108         108  Alabama                 0.0
1971    162         162  Alabama                 0.0
1972    216         216  Alabama                 0.0

      State.Minimum.Wage.2020.Dollars  Federal.Minimum.Wage  \
Year
1968                              0.0                  1.15
1969                              0.0                  1.15
1970                              0.0                  1.30
1971                              0.0                  1.30
1972                              0.0                  1.60

      Federal.Minimum.Wage.2020.Dollars  Effective.Minimum.Wage  \
Year
1968                               8.55                    1.15
1969                               8.11                    1.15
1970                               8.67                    1.30
1971                               8.30                    1.30
1972                               9.90                    1.60

      Effective.Minimum.Wage.2020.Dollars  CPI.Average  \
Year
1968                                 8.55         34.8
1969                                 8.11         36.7
1970                                 8.67         38.8
1971                                 8.30         40.5
1972                                 9.90         41.8

     Department.Of.Labor.Uncleaned.Data  \
Year
1968                                ...
1969                                ...
1970                                ...
1971                                ...
1972                                ...

      Department.Of.Labor.Cleaned.Low.Value  \
Year
1968                                    0.0
1969                                    0.0
1970                                    0.0
1971                                    0.0
1972                                    0.0

      Department.Of.Labor.Cleaned.Low.Value.2020.Dollars  \
Year
1968                                                0.0
1969                                                0.0
1970                                                0.0
1971                                                0.0
1972                                                0.0

      Department.Of.Labor.Cleaned.High.Value  \
Year
1968                                     0.0
1969                                     0.0
1970                                     0.0
1971                                     0.0
1972                                     0.0

      Department.Of.Labor.Cleaned.High.Value.2020.Dollars Footnote
Year
1968                                                0.0        NaN
1969                                                0.0        NaN
1970                                                0.0        NaN
1971                                                0.0        NaN
1972                                                0.0        NaN

In [35]:
gb1.index.name

'Year'

In [41]:
act_min_wage = pd.DataFrame()

for name, group in df.groupby("State"):
    if act_min_wage.empty:
        print('name 1 is ', name)
        act_min_wage = group.set_index("Year")[["Department.Of.Labor.Cleaned.Low.Value.2020.Dollars"]].rename(columns={"Department.Of.Labor.Cleaned.Low.Value.2020.Dollars":name})
    else:
        print('name 2 is ', name)
        act_min_wage = act_min_wage.join(group.set_index("Year")[["Department.Of.Labor.Cleaned.Low.Value.2020.Dollars"]].rename(columns={"Department.Of.Labor.Cleaned.Low.Value.2020.Dollars":name}))

act_min_wage.head()

name 1 is  Alabama
name 2 is  Alaska
name 2 is  Arizona
name 2 is  Arkansas
name 2 is  California
name 2 is  Colorado
name 2 is  Connecticut
name 2 is  Delaware
name 2 is  District of Columbia
name 2 is  Florida
name 2 is  Georgia
name 2 is  Guam
name 2 is  Hawaii
name 2 is  Idaho
name 2 is  Illinois
name 2 is  Indiana
name 2 is  Iowa
name 2 is  Kansas
name 2 is  Kentucky
name 2 is  Louisiana
name 2 is  Maine
name 2 is  Maryland
name 2 is  Massachusetts
name 2 is  Michigan
name 2 is  Minnesota
name 2 is  Mississippi
name 2 is  Missouri
name 2 is  Montana
name 2 is  Nebraska
name 2 is  Nevada
name 2 is  New Hampshire
name 2 is  New Jersey
name 2 is  New Mexico
name 2 is  New York
name 2 is  North Carolina
name 2 is  North Dakota
name 2 is  Ohio
name 2 is  Oklahoma
name 2 is  Oregon
name 2 is  Pennsylvania
name 2 is  Puerto Rico
name 2 is  Rhode Island
name 2 is  South Carolina
name 2 is  South Dakota
name 2 is  Tennessee
name 2 is  Texas
name 2 is  U.S. Virgin Islands
name 2 is  Utah
name 2 is  Vermont
name 2 is  Virginia
name 2 is  Washington
name 2 is  West Virginia
name 2 is  Wisconsin
name 2 is  Wyoming

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Year,,,,,,,,,,,,,,,,,,,,,
1968,0.0,15.61,3.48,1.16,12.26,7.43,10.41,9.29,9.29,0.0,...,0.0,0.00,NaN,7.43,10.41,0.0,11.89,7.43,9.29,8.92
1969,0.0,14.80,3.30,1.10,11.63,7.05,9.87,8.81,8.81,0.0,...,0.0,0.00,NaN,7.05,9.87,0.0,11.28,7.05,8.81,8.46
1970,0.0,14.00,3.12,7.33,11.00,6.67,10.67,8.33,10.67,0.0,...,0.0,0.00,NaN,6.67,10.67,0.0,10.67,6.67,8.67,8.67
1971,0.0,13.41,2.99,7.03,10.54,6.39,10.22,7.98,10.22,0.0,...,0.0,0.00,NaN,6.39,10.22,0.0,10.22,6.39,8.30,8.30
1972,0.0,12.99,2.90,7.43,10.21,6.19,11.45,9.90,9.90,0.0,...,0.0,8.66,NaN,7.43,9.90,0.0,9.90,7.43,8.97,9.28

In [43]:
act_min_wage.describe()

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
count,53.0,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,...,53.0,53.000000,42.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,0.0,9.917736,2.917358,7.139245,9.101132,6.881698,9.212830,7.818679,8.919245,2.415283,...,0.0,5.816038,6.980238,7.079245,9.057358,6.163019,8.826038,7.486226,7.914528,5.313208
std,0.0,1.852213,4.102247,1.459132,1.418712,1.921086,1.106907,1.307834,1.932959,3.882305,...,0.0,2.240879,1.815899,0.824707,1.093119,2.749633,2.147933,0.866017,0.778113,2.004899
min,0.0,7.620000,0.000000,1.100000,6.630000,3.970000,7.040000,4.550000,5.690000,0.000000,...,0.0,0.000000,4.430000,4.950000,7.030000,0.000000,4.550000,5.770000,6.630000,2.340000
25%,0.0,8.590000,0.000000,6.780000,8.000000,5.250000,8.200000,7.320000,7.420000,0.000000,...,0.0,4.990000,5.225000,6.610000,8.060000,6.250000,7.610000,6.850000,7.320000,3.500000
50%,0.0,9.260000,0.000000,7.210000,9.010000,6.670000,9.430000,8.170000,8.840000,0.000000,...,0.0,6.360000,7.105000,7.220000,9.240000,7.210000,9.700000,7.370000,7.810000,5.550000
75%,0.0,10.510000,8.290000,7.740000,9.710000,8.430000,9.870000,8.620000,9.600000,8.210000,...,0.0,7.350000,8.270000,7.660000,9.820000,7.810000,10.180000,7.930000,8.340000,6.820000
max,0.0,15.610000,12.140000,10.000000,13.000000,12.140000,11.450000,9.900000,14.160000,8.790000,...,0.0,8.660000,10.620000,8.600000,11.090000,9.090000,13.660000,9.430000,9.980000,9.280000

In [44]:
act_min_wage.corr().head(5)

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alaska,NaN,1.000000,0.037101,-0.332127,0.622245,-0.078678,0.646909,0.260265,0.271810,-0.193062,...,NaN,-0.507366,0.305388,-0.017546,0.615675,-0.593675,0.378141,0.056924,0.683108,0.726771
Arizona,NaN,0.037101,1.000000,0.271834,0.639006,0.820730,0.555455,0.477781,0.723523,0.907295,...,NaN,0.398732,-0.421255,0.413915,0.624314,0.096048,0.691863,0.663311,0.014723,0.288171
Arkansas,NaN,-0.332127,0.271834,1.000000,0.030265,0.333597,0.183662,0.107639,0.433775,0.340509,...,NaN,0.520381,0.080528,0.208586,0.236875,0.572595,0.130825,0.504703,-0.069024,-0.235369
California,NaN,0.622245,0.639006,0.030265,1.000000,0.649967,0.881831,0.518481,0.727373,0.443946,...,NaN,-0.109316,-0.061610,0.367924,0.894617,-0.216247,0.816087,0.492809,0.382444,0.598739

In [45]:
df_issue = df[df['Department.Of.Labor.Cleaned.Low.Value.2020.Dollars']==0]

In [47]:
df_issue['State'].unique()

array(['Alabama', 'Florida', 'Georgia', 'Illinois', 'Iowa', 'Kansas',
       'Louisiana', 'Mississippi', 'Missouri', 'Montana',
       'South Carolina', 'Tennessee', 'Texas', 'Virginia', 'Arizona'],
      dtype=object)

In [49]:
import numpy as np

In [51]:
# axis 1 == columns. 0,default, is for rows
act_min_wage.replace(0, np.nan).dropna(axis=1).corr().head()

,Alaska,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Guam,Hawaii,Idaho,...,Oregon,Pennsylvania,Rhode Island,South Dakota,Utah,Vermont,Washington,West Virginia,Wisconsin,Wyoming
Alaska,1.000000,-0.332127,0.622245,-0.078678,0.646909,0.260265,0.271810,0.787515,0.630212,0.371745,...,0.010495,0.590298,0.610099,-0.287259,-0.017546,0.615675,0.378141,0.056924,0.683108,0.726771
Arkansas,-0.332127,1.000000,0.030265,0.333597,0.183662,0.107639,0.433775,0.037006,0.324870,0.008276,...,0.399650,0.065998,0.160773,0.826094,0.208586,0.236875,0.130825,0.504703,-0.069024,-0.235369
California,0.622245,0.030265,1.000000,0.649967,0.881831,0.518481,0.727373,0.411729,0.610784,0.542006,...,0.572160,0.241669,0.816544,0.171242,0.367924,0.894617,0.816087,0.492809,0.382444,0.598739
Colorado,-0.078678,0.333597,0.649967,1.000000,0.520931,0.581162,0.798145,-0.152291,0.291995,0.436981,...,0.733803,-0.229508,0.559646,0.519677,0.538775,0.581318,0.721208,0.623479,-0.101133,0.095454
Connecticut,0.646909,0.183662,0.881831,0.520931,1.000000,0.586472,0.700081,0.587469,0.674581,0.536894,...,0.480491,0.408964,0.829952,0.228521,0.307922,0.911003,0.760697,0.484080,0.468287,0.752009

In [61]:
def get_min_wage(year, state):
    try:
        return act_min_wage.loc[year][state]
    except:
        return np.nan

In [58]:
get_min_wage(2012, "Colorado")

np.float64(8.61)

In [55]:
%%time
# time will give us the total time to perform some cell's operation.

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 3.81 µs

In [63]:
%%time
unemp_county = pd.read_csv("sample_data/unemployment.csv")
unemp_county.head()

unemp_county['min_wage'] = list(map(get_min_wage, unemp_county['Year'], unemp_county['State']))

CPU times: user 1.72 s, sys: 1.65 ms, total: 1.73 s
Wall time: 1.73 s

In [64]:
unemp_county.head()

   Year     Month        State         County  Rate  min_wage
0  2015  February  Mississippi  Newton County   6.1       0.0
1  2015  February  Mississippi  Panola County   9.4       0.0
2  2015  February  Mississippi  Monroe County   7.9       0.0
3  2015  February  Mississippi   Hinds County   6.1       0.0
4  2015  February  Mississippi  Kemper County  10.6       0.0

In [65]:
unemp_county[['Rate','min_wage']].corr()

              Rate  min_wage
Rate      1.000000 -0.204895
min_wage -0.204895  1.000000

In [66]:
unemp_county[['Rate','min_wage']].cov()

              Rate  min_wage
Rate      5.519077 -1.395606
min_wage -1.395606  8.406162

In [71]:
print(unemp_county.shape)
print(len(unemp_county))

(52121, 6)
52121

In [75]:
pres16 = pd.read_csv('sample_data/pres16results.csv')

In [76]:
pres16.head()

,county,fips,cand,st,pct_report,votes,total_votes,pct,lead
0,NaN,US,Donald Trump,US,0.9951,60350241.0,127592176.0,0.472993,Donald Trump
1,NaN,US,Hillary Clinton,US,0.9951,60981118.0,127592176.0,0.477938,Donald Trump
2,NaN,US,Gary Johnson,US,0.9951,4164589.0,127592176.0,0.032640,Donald Trump
3,NaN,US,Jill Stein,US,0.9951,1255968.0,127592176.0,0.009844,Donald Trump
4,NaN,US,Evan McMullin,US,0.9951,451636.0,127592176.0,0.003540,Donald Trump

In [82]:
county_2015 = unemp_county[(unemp_county['Year']==2015) & (unemp_county['Month']=='February')]

In [83]:
county_2015.head()

   Year     Month        State         County  Rate  min_wage
0  2015  February  Mississippi  Newton County   6.1       0.0
1  2015  February  Mississippi  Panola County   9.4       0.0
2  2015  February  Mississippi  Monroe County   7.9       0.0
3  2015  February  Mississippi   Hinds County   6.1       0.0
4  2015  February  Mississippi  Kemper County  10.6       0.0

In [84]:
county_2015['NewCol'] = 1   # might trigger SettingWithCopyWarning

/tmp/ipython-input-636552537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  county_2015['NewCol'] = 1   # might trigger SettingWithCopyWarning

In [85]:
county_2015.head()

   Year     Month        State         County  Rate  min_wage  NewCol
0  2015  February  Mississippi  Newton County   6.1       0.0       1
1  2015  February  Mississippi  Panola County   9.4       0.0       1
2  2015  February  Mississippi  Monroe County   7.9       0.0       1
3  2015  February  Mississippi   Hinds County   6.1       0.0       1
4  2015  February  Mississippi  Kemper County  10.6       0.0       1

In [86]:
county_2015 = county_2015.drop(columns=['NewCol'])
county_2015.head()

   Year     Month        State         County  Rate  min_wage
0  2015  February  Mississippi  Newton County   6.1       0.0
1  2015  February  Mississippi  Panola County   9.4       0.0
2  2015  February  Mississippi  Monroe County   7.9       0.0
3  2015  February  Mississippi   Hinds County   6.1       0.0
4  2015  February  Mississippi  Kemper County  10.6       0.0

In [88]:
pres16['st'].unique()

array(['US', 'CA', 'FL', 'TX', 'NY', 'PA', 'IL', 'OH', 'MI', 'NC', 'GA',
       'VA', 'NJ', 'MA', 'WI', 'MN', 'MO', 'WA', 'IN', 'CO', 'TN', 'MD',
       'SC', 'AL', 'AZ', 'LA', 'KY', 'OR', 'CT', 'IA', 'OK', 'MS', 'KS',
       'NV', 'AR', 'UT', 'NE', 'NM', 'ME', 'NH', 'WV', 'ID', 'MT', 'RI',
       'DE', 'HI', 'SD', 'ND', 'VT', 'DC', 'WY', 'AK', nan], dtype=object)

In [107]:
top_candidates = pres16.head(10)['cand'].values
print(top_candidates, type(top_candidates))

['Donald Trump' 'Hillary Clinton' 'Gary Johnson' 'Jill Stein'
 'Evan McMullin' 'Darrell Castle' 'Gloria La Riva' 'Rocky De La Fuente'
 ' None of these candidates' 'Richard Duncan'] <class 'numpy.ndarray'>

In [110]:
type(np.array(pres16['cand'].head(10)))
#print(top_candidates)

numpy.ndarray

In [113]:
np.array(pres16['cand'].head(10))

array(['Donald Trump', 'Hillary Clinton', 'Gary Johnson', 'Jill Stein',
       'Evan McMullin', 'Darrell Castle', 'Gloria La Riva',
       'Rocky De La Fuente', ' None of these candidates',
       'Richard Duncan'], dtype=object)

In [115]:
import pandas as pd

df = pd.read_csv("sample_data/diamonds.csv", index_col=0)
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [116]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.5+ MB

In [118]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [124]:
np.shape(df)

(53940, 10)

In [127]:
df.index

Index([    1,     2,     3,     4,     5,     6,     7,     8,     9,    10,
       ...
       53931, 53932, 53933, 53934, 53935, 53936, 53937, 53938, 53939, 53940],
      dtype='int64', length=53940)

In [129]:
print(df.index.name)

None

In [133]:
df.iloc[:9, 0]

1    0.23
2    0.21
3    0.23
4    0.29
5    0.31
6    0.24
7    0.24
8    0.26
9    0.22
Name: carat, dtype: float64